### ISSUE TITLE
Fix eccentricity in stepper motor cog

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/circular_knitic#10]
The cog on the stepper motor wobbles quite a bit, which isn't helping how smoothly it runs.

**Comment by amcewen** [comment]
A new cog (which will be cut as part of #9) might fix things.  Otherwise maybe it's because the mounting boss is for an imperial shaft and the shaft is metric. (Am I remembering that correctly @huffeec?)

**Comment by huffeec** [comment]
Yes, the [motor](http://www.active-robots.com/3330-0-57sth56-nema-23-bipolar-precision-gearless-stepper) is 1/4" the [shaft mount](http://www.active-robots.com/pololu-universal-aluminum-mounting-hub-6mm-shaft-pair-m3-holes) is 6mm
I think it's more how the cog is mounted.
Rob replaced the cog to fix this.
