### ISSUE TITLE
Knitic Arduino is low on magic smoke - Replace Arduino

### ISSUE THREAD

**Issue by paulgeering** [DoESLiverpool/circular_knitic#13]
So, in a rush to head home on Saturday, I kinda blew up the arduino (again) by connecting the power backwards.

I will bring a replacement Arduino in on Monday morning, and swap it with the blown one.
Sorry

**Comment by paulgeering** [comment]
New arduino installed. Knitic electronics tested and working.

**Comment by DefProc** [comment]
@paulgeering just a thought, but this might not be a problem with an official board, the reverse polarity protection diode should trip the power supply by shorting it, rather than blowing the regulator
