### ISSUE TITLE
Cut new 5mm acrylic pieces

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/circular_knitic#9]
We need an assortment of the 5mm acrylic parts cutting:

 * [x] [Cogs](https://github.com/DoESLiverpool/circular_knitic/blob/master/2D_laser_cut/SVG/bottom_surface_motor_gears_6mm.svg)
 * [x] [Upper surface](https://github.com/DoESLiverpool/circular_knitic/blob/master/2D_laser_cut/SVG/upper_surface_5mm.svg)

**Comment by JackiePease** [comment]
Done
